version: "3.4"

services:

  eventstore.db:
    image: eventstore/eventstore:22.10.3-alpha-arm64v8
#   image: eventstore/eventstore:22.10.3-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  redis:
    image: redis:7.2-alpine3.18
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-volume-data
        target: /data

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  redis-volume-data:
